### PR TITLE
refactor 'setResourceContent' method

### PR DESCRIPTION
**Pull request by stoicflame**
I'm working on an implementation of `IWebdavStore` that uses Amazon S3 as a back-end. This refactor removes some unused parameters and as a needed `contentLength` parameter to the `setResourceContent` method to make the S3 implementation easier.

In addition to the request to merge these changes, I have a question: I'd be happy to contribute my S3 implementation to the project. If I submitted another pull request including this code, would it be accepted? Or is that outside the scope of this project?

It seems like it's not outside the scope of the project, since the project already comes with a default filesystem implementation.

Thanks!

### CODE REVIEW

**Comment by jdcasey** [comment]
The code itself looks reasonable. Regarding your proposed contribution, this codebase was mainly aimed at adapting an older project that I found. I'd like to take some time before I say yes, and make sure the licensing and copyright info is relatively clear. I wouldn't want your contribution to end up in a project where copyright or licensing is murky.

**Comment by stoicflame** [comment]
Well, I'll send another pull request with the s3 implementation and let you do what you want with it.

In the meantime, can we get this merged and built?

**Comment by stoicflame** [comment]
Cool. Thanks.

What's your deploy process? Is there a build server somewhere?

**Comment by jdcasey** [comment]
I have a server in my basement that I've been using for CI (Jenkins). I have Docker on it, and I have a Docker image that can do a maven release in a cleanroom-ish way:

http://github.com/Commonjava/docker-maven-release

Other than the fancy Docker image, it's just `mvn clean release:prepare release:perform` under the covers.

**Pull request merged**
